package com.shopflow.backend.controller;

import com.shopflow.backend.server.RequestContext;
import com.shopflow.backend.server.Router;
import com.shopflow.backend.service.AuthService;
import com.shopflow.backend.service.ReportService;
import com.shopflow.common.json.Json;

import java.util.Map;

/**
 * Endpoints under /api/reports. Every report is generated by the Python
 * script invoked through {@link ReportService}; this controller only
 * shapes the response.
 *
 * <pre>
 * GET /api/reports/summary        full dashboard payload (runs Python)
 * GET /api/reports/low-stock      low stock products only (runs Python)
 * GET /api/reports/health         whether Python and the script are available
 * GET /api/health                 open liveness endpoint
 * </pre>
 */
public class ReportController {

    private final ReportService reportService;
    private final AuthService authService;

    public ReportController(ReportService reportService, AuthService authService) {
        this.reportService = reportService;
        this.authService = authService;
    }

    public void register(Router router) {
        router.get("/api/reports/summary", this::summary);
        router.get("/api/reports/low-stock", this::lowStock);
        router.get("/api/reports/health", this::health);
        router.open("GET", "/api/health", this::liveness);
    }

    private Object summary(RequestContext ctx) {
        return reportService.summary();
    }

    private Object lowStock(RequestContext ctx) {
        Map<String, Object> report = reportService.summary();
        return Json.map(
                "items", Json.nestedList(report, "lowStock"),
                "generatedBy", report.get("generatedBy"),
                "generatedAt", report.get("generatedAt"));
    }

    private Object health(RequestContext ctx) {
        Map<String, Object> health = reportService.health();
        health.put("activeSessions", authService.activeSessionCount());
        return health;
    }

    private Object liveness(RequestContext ctx) {
        return Json.map(
                "status", "up",
                "service", "shopflow-backend",
                "time", System.currentTimeMillis());
    }
}
